public class NewCalc extends javax.swing.JFrame {


    public NewCalc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        num1Text = new javax.swing.JTextField();
        num2Text = new javax.swing.JTextField();
        num2Label = new javax.swing.JLabel();
        num1Label = new javax.swing.JLabel();
        adder = new javax.swing.JRadioButton();
        subtracter = new javax.swing.JRadioButton();
        multiplyer = new javax.swing.JRadioButton();
        divider = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resulttxtArea = new javax.swing.JTextArea();
        resultLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        num2Label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        num2Label.setText("Num2");

        num1Label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        num1Label.setText("Num1");

        buttonGroup1.add(adder);
        adder.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        adder.setText("Add");
        adder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adderMouseClicked(evt);
            }
        });

        buttonGroup1.add(subtracter);
        subtracter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        subtracter.setText("Subtract");
        subtracter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subtracterMouseClicked(evt);
            }
        });

        buttonGroup1.add(multiplyer);
        multiplyer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        multiplyer.setText("Multiply");
        multiplyer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                multiplyerMouseClicked(evt);
            }
        });

        buttonGroup1.add(divider);
        divider.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        divider.setText("Divide");
        divider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dividerMouseClicked(evt);
            }
        });

        resulttxtArea.setColumns(20);
        resulttxtArea.setRows(5);
        jScrollPane1.setViewportView(resulttxtArea);

        resultLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        resultLabel.setText("Result");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(num1Text)
                                .addComponent(num1Label, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(adder)
                                .addComponent(subtracter)
                                .addComponent(multiplyer)
                                .addComponent(divider)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(num2Text)
                            .addComponent(num2Label, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 73, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(num1Text, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(num2Text))
                .addGap(32, 32, 32)
                .addComponent(adder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(subtracter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(multiplyer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(divider)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adderMouseClicked
        int a, b, res;
        a=Double.parseDouble(num1Text.getText());
        b=Double.parseDouble(num2Text.getText());
        res=aad+bad;
        resulttxtArea.setText("Added: "+resad+"\n");

    }//GEN-LAST:event_adderMouseClicked

    private void subtracterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subtracterMouseClicked
        int a, b, res;
        a=Double.parseDouble(num1Text.getText());
        b=Double.parseDouble(num2Text.getText());
        res=asub-bsub;
        resulttxtArea.setText("Subtracted: "+ressub+"\n");
    }//GEN-LAST:event_subtracterMouseClicked

    private void multiplyerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiplyerMouseClicked
       int a, b, res;
        a=Double.parseDouble(num1Text.getText());
        b=Double.parseDouble(num2Text.getText());
        res=amul*bmul;
        resulttxtArea.setText("Multiplied: "+resmul+"\n");
    }//GEN-LAST:event_multiplyerMouseClicked

    private void dividerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dividerMouseClicked
        float a, b, res;
        a=Double.parseDouble(num1Text.getText());
        b=Double.parseDouble(num2Text.getText());
        res=adiv/bdiv;
        resulttxtArea.setText("Divided: "+resdiv+"\n");
    }//GEN-LAST:event_dividerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewCalc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton adder;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton divider;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton multiplyer;
    private javax.swing.JLabel num1Label;
    private javax.swing.JTextField num1Text;
    private javax.swing.JLabel num2Label;
    private javax.swing.JTextField num2Text;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JTextArea resulttxtArea;
    private javax.swing.JRadioButton subtracter;
    // End of variables declaration//GEN-END:variables
}
